### PR TITLE
#67 BDD.pathCount/satCount return a BigInteger.

### LINKED ISSUE #67: BDD.satCount(BDDVarSet) may produce wrong results
Due to overflow, it may return `1`. See also https://gitlab.eclipse.org/eclipse/escet/escet/-/issues/951#note_2684236.

### PR DESCRIPTION
**Pull request by dhendriks**
- `BDD.pathCount`/`satCount` return a `BigInteger` rather than a `double`.
- The `countcache` now stores `BigInteger`s as well.
- Gives better precision for larger BDDs.
- Prevents wrong results for very large BDDs.

Fixes #67

### CODE REVIEW

File: src/main/java/com/github/javabdd/BDDDomain.java [hunk 1]
```diff
@@ -405,7 +405,7 @@ public BigInteger[] getVarIndices(BDD that) {
      */
     public BigInteger[] getVarIndices(BDD that, int max) {
         BDDVarSet myvarset = set(); // can't use var here, must respect subclass a factory may provide
-        int n = (int)that.satCount(myvarset);
+        int n = that.satCount(myvarset).intValueExact();
```
Comment (wytseoortwijn) [inline src/main/java/com/github/javabdd/BDDDomain.java:408]: Nice that `intValueExact` throws an exception if `that.satCount(myvarset)` goes out of range for the integer type. Now `n` can no longer become negative due to overflows.

File: src/main/java/com/github/javabdd/JFactory.java [hunk 2]
```diff
@@ -1076,6 +1077,20 @@ BddCacheData copy() {
         }
     }
 
+    private static class BddCacheDataBI extends BddCacheData {
```
Comment (wytseoortwijn) [inline src/main/java/com/github/javabdd/JFactory.java:1080]: Why not simply change the `BddCacheDataD` class? That class only seems to be used for satcount and pathcount. Adding this extra class comes with some extra complexity. For example, I'm not sure whether `BddCache#copy` now works correctly. This method now needs an extra case distinction for `BddCacheDataBI` entries.

File: src/main/java/com/github/javabdd/JFactory.java [hunk 3]
```diff
@@ -6277,110 +6292,92 @@ void varprofile_rec(int r, int[] varprofile) {
...
 
         miscid = CACHEID_SATCOU;
-        if (!ZDD) {
-            size = Math.pow(2.0, LEVEL(r));
-        }
-
-        return size * satcount_rec(r);
-    }
-
-    double bdd_satcountset(int r, int varset) {
```
Comment (wytseoortwijn) [inline src/main/java/com/github/javabdd/JFactory.java:6338]: Has this method been removed on purpose?

File: src/main/java/com/github/javabdd/JFactory.java [hunk 4]
```diff
@@ -6277,110 +6292,92 @@ void varprofile_rec(int r, int[] varprofile) {
...
 
-    double satcount_rec(int root) {
-        BddCacheDataD entry;
-        double size, s;
+    BigInteger satcount_rec(int root) {
+        BddCacheDataBI entry;
 
         if (root < 2) {
-            return root;
+            return (root == 0) ? BigInteger.ZERO : BigInteger.ONE;
```
Comment (wytseoortwijn) [inline src/main/java/com/github/javabdd/JFactory.java:6357]: Could also use `BigInteger#valueOf(root)`?

**Review by wytseoortwijn — CHANGES_REQUESTED** [review]

File: src/main/java/com/github/javabdd/JFactory.java (hunk 3 above)
Comment (dhendriks) [reply src/main/java/com/github/javabdd/JFactory.java:6338]: Yes, it is not used anywhere, and is not public API.

File: src/main/java/com/github/javabdd/JFactory.java (hunk 4 above)
Comment (dhendriks) [reply src/main/java/com/github/javabdd/JFactory.java:6357]: Changed.

File: src/main/java/com/github/javabdd/JFactory.java (hunk 2 above)
Comment (dhendriks) [reply src/main/java/com/github/javabdd/JFactory.java:1066]: I fixed the `copy` method. I removed `BddCacheDataD`. So, it is kind of like renaming `BddCacheDataD` to `BddCacheDataBI` and changing the field from `double` to `BigInteger`.

**Review by wytseoortwijn — APPROVED** [review]
